# Generated by Django 3.0.8 on 2020-12-06 19:23

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to=user_profile.models.get_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to=user_profile.models.get_path),
        ),
    ]
